# Generated by Django 2.0 on 2017-12-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171221_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
